version: "3.0"
services:

    yarrrml_transform:
        image: markw/yarrml-parser-ejp:0.0.4
        container_name: yarrrml_transform
        ports:
            - "3000:3000"
        volumes:
            - ./data:/data

    rdfizer:
        image: markw/sdmrdfizer_ejp:0.5.0
        container_name: rdfizer
        ports:
            - "4000:4000"
        volumes:
            - ./data:/data
            - ./config:/config
