mapping:
  20230306105653860869_source_cde_test:
    graph: this:$(uniqid)_Context
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Role
      predicate: sio:SIO_000020
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: Identifier
      predicate: rdfs:label
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_ID
  20230306105653860885_source_cde_test:
    graph: this:$(uniqid)_Context
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Role
      predicate: sio:SIO_000228
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Attribute
      predicate: sio:SIO_000008
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: Person
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_Entity
  20230306105653860893_source_cde_test:
    graph: this:$(uniqid)_Context
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Process
      predicate: sio:SIO_000356
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: Patient role
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Role
  20230306105653860902_source_cde_test:
    graph: this:$(uniqid)_Context
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Target
      predicate: sio:SIO_000291
    - objects:
        type: iri
        value: $(agent_id)
      predicate: sio:SIO_000139
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Input
      predicate: sio:SIO_000230
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Output
      predicate: sio:SIO_000229
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    - objects:
        type: iri
        value: $(process_type)
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(model) measurement process
      predicate: rdfs:label
    - objects:
        datatype: xsd:string
        value: $(comments)
      predicate: rdfs:comments
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Process
  20230306105653860909_source_cde_test:
    graph: this:$(uniqid)_Context
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Route
      predicate: sio:SIO_000362
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: $(agent_type)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: $(agent_id)
  20230306105653860917_source_cde_test:
    graph: this:$(uniqid)_Context
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Attribute
      predicate: sio:SIO_000628
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: $(output_type)
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(model) measurement output
      predicate: rdfs:label
    - objects:
        datatype: xsd:string
        value: $(value_string)
      predicate: sio:SIO_000300
    - objects:
        datatype: xsd:date
        value: $(value_date)
      predicate: sio:SIO_000300
    - objects:
        datatype: xsd:float
        value: $(value_float)
      predicate: sio:SIO_000300
    - objects:
        datatype: xsd:float
        value: $(value_integer)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Output
  20230306105653860922_source_cde_test:
    graph: this:$(uniqid)_Context
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: $(input_type)
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(model) input
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Input
  20230306105653860928_source_cde_test:
    graph: this:$(uniqid)_Context
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: $(target_type)
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(model) target
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Target
  20230306105653860933_source_cde_test:
    graph: this:$(uniqid)_Context
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: $(route_type)
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(model) route
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Route
  20230306105653860940_source_cde_test:
    graph: this:$(uniqid)_Context
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    - objects:
        type: iri
        value: $(attribute_type)
      predicate: rdf:type
    - objects:
        type: iri
        value: $(attribute_id)
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(model) attribute
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Attribute
  20230306105653860944_source_cde_test:
    graph: this:$(uniqid)_Context
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(model) agent
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Agent
  20230306105653860950_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(uniqid)_Startdate
      predicate: sio:SIO_000680
    - objects:
        type: iri
        value: this:$(uniqid)_Enddate
      predicate: sio:SIO_000681
    - objects:
        type: iri
        value: this:$(pid)_Timeline
      predicate: sio:SIO_000068
    - objects:
        type: iri
        value: obo:NCIT_C25616
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(uniqid)
      predicate: sio:SIO_000300
    - objects:
        type: iri
        value: this:$(pid)_$(context_id)_Mayor_context
      predicate: sio:SIO_000068
    sources:
    - source_cde_test
    subjects: this:$(uniqid)_Context
  20230306105653860955_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_Person
      predicate: sio:SIO_000332
    - objects:
        type: iri
        value: sio:SIO_000417
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:NCIT_C54576
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_Timeline
  20230306105653860960_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_Identifier
      predicate: sio:SIO_000671
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_Person
  20230306105653860965_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000031
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: '$(model) startdate: $(startdate)'
      predicate: rdfs:label
    - objects:
        datatype: xsd:date
        value: $(startdate)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(uniqid)_Startdate
  20230306105653860969_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000032
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: '$(model) enddate: $(enddate)'
      predicate: rdfs:label
    - objects:
        datatype: xsd:date
        value: $(enddate)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(uniqid)_Enddate
  20230306105653860974_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_Identifier
  20230306105653860979_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(context_id)_Startdate
      predicate: sio:SIO_000680
    - objects:
        type: iri
        value: this:$(pid)_$(context_id)_Enddate
      predicate: sio:SIO_000681
    - objects:
        type: iri
        value: obo:NCIT_C25616
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(context_id)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(context_id)_Mayor_context
  20230306105653860983_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000031
      predicate: rdf:type
    - objects:
        datatype: xsd:date
        value: $(context_startdate)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(context_id)_Startdate
  20230306105653860987_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000032
      predicate: rdf:type
    - objects:
        datatype: xsd:date
        value: $(context_enddate)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(context_id)_Enddate
prefixes:
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: https://sio.semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

