mapping:
  20221122114818837321_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(uniqid)_Role
      predicate: ejprd_usecase_flash:has_user_role
    - objects:
        type: iri
        value: ejprd_usecase_flash:Clinical_doing_research
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(user)
      predicate: rdfs:label
    - objects:
        type: iri
        value: $(user_id)
      predicate: ejprd_usecase_flash:has_id
    sources:
    - source_cde_test
    subjects: this:$(uniqid)_User
  20221122114818837338_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(uniqid)_User
      predicate: ejprd_usecase_flash:user_role_of
    - objects:
        type: iri
        value: ejprd_usecase_flash:Clinical_doing_research_role
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(as_a)
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(uniqid)_Role
  20221122114818837346_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(uniqid)_User
      predicate: ejprd_usecase_flash:use_case_of_user
    - objects:
        type: iri
        value: this:$(uniqid)_Specific_goal
      predicate: ejprd_usecase_flash:use_case_involves_specific_goal
    - objects:
        type: iri
        value: this:$(uniqid)_Contextual_goal
      predicate: ejprd_usecase_flash:such_that_I_can
    - objects:
        type: iri
        value: ejprd_usecase_flash:Use_case
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(sum)
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(uniqid)_Use_case
  20221122114818837350_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: ejprd_usecase_flash:SpecificGoal
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(such_that_I_can)
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(uniqid)_Specific_goal
  20221122114818837354_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: ejprd_usecase_flash:ContextualGoal
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(I_would_like_to)
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(uniqid)_Contextual_goal
prefixes:
  ejprd_usecase_flash: http://purl.org/ejp-rd/ontologies/2022/6/ejprd-usecase-flash#
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

