mapping:
  20230117115905411286_source_cde_test:
    graph: this:$(context_id)_Context
    predicateobject:
    - objects:
        datatype: $(datatype)
        value: $(value)
      predicate: sio:SIO_000300
    - objects:
        datatype: $(datatype2)
        value: $(value)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Output
prefixes:
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: https://sio.semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

