PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sio: <http://semanticscience.org/resource/> 
PREFIX biolink: <https://w3id.org/biolink/vocab/> 
PREFIX obo: <http://purl.obolibrary.org/obo/> 


SELECT ?id_value WHERE { 

  GRAPH <http://localhost:8890/DAV/home/LDP/test1> { 

	?entity rdf:type biolink:Case .
        ?entity rdf:type sio:SIO_000498 .
        ?entity sio:has-role ?role .

        ?ID rdf:type sio:SIO_000115 .
        ?ID rdf:type biolink:ID.
        ?ID sio:denotes ?role .
        ?ID sio:SIO_000300 ?id_value .

  }  
} 



############################### 


PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sio: <http://semanticscience.org/resource/> 
PREFIX biolink: <https://w3id.org/biolink/vocab/> 
PREFIX obo: <http://purl.obolibrary.org/obo/> 


CONSTRUCT {

 ?entity rdf:type biolink:Case .
 ?entity biolink:ID ?ID .
 ?ID rdf:type biolink:ID .
 ?ID biolink:hasnumerical_value ?id_value .

} WHERE { 

  GRAPH <http://localhost:8890/DAV/home/LDP/test1> { 

	?entity rdf:type biolink:Case .
        ?entity rdf:type sio:SIO_000498 .
        ?entity sio:has-role ?role .

        ?ID rdf:type sio:SIO_000115 .
        ?ID rdf:type biolink:ID.
        ?ID sio:denotes ?role .
        ?ID sio:SIO_000300 ?id_value .

  }  
} 


#################################


PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX http: <http://www.w3.org/2011/http#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sio: <http://semanticscience.org/resource/> 
PREFIX biolink: <https://w3id.org/biolink/vocab/> 
PREFIX obo: <http://purl.obolibrary.org/obo/> 
PREFIX : <https://bnode/>

CONSTRUCT {
  _:bnode biolink:hasID _:bnode2 .
  _:bnode rdf:type biolink:Case .
  _:bnode2 biolink:hasnumerical_value ?id_value .
  _:bnode2 rdf:type biolink:ID .

} WHERE {
  ?entity rdf:type biolink:Case .
  ?entity rdf:type sio:SIO_000498 .
  ?entity sio:has-role ?role .
  ?ID rdf:type sio:SIO_000115 .
  ?ID rdf:type biolink:ID.
  ?ID sio:denotes ?role .
  ?ID sio:SIO_000300 ?id_value .
  ?role rdf:type obo:OBI_0000093 .
}